### ISSUE TITLE
CursorLine looks black undev nvim 0.4.4

### ISSUE THREAD

**Issue by ghost** [flrnd/candid.vim#8] opened 2020-09-21 21:31 UTC
I am currently using this colorscheme, but the CursorLine does not seem to work properly. Using nvim 0.4.4 and I have set termguicolors and I am using st-256color
![2020-09-21-141847_1654x256_scrot](https://user-images.githubusercontent.com/22781207/93823681-18dff800-fc17-11ea-997e-cc6807d1659f.png)

**Comment by flrnd** [comment] 2020-09-22 09:31
Hey @hackedWifi, I'm afraid it's a problem on your end because right now it's working as intended. 

`CursorLine` it's using pale_black as color, `call <sid>hi('CursorLine', s:none, s:pale_black, 'none', {}) ` and pale_black is defined with the same color as the background: `"black": get(s:color_store, "black", {'gui': '#2f343f', 'cterm256': '232'})`.

Probably a problem with your terminal truecolor support. Hope it helps. Closing this issue.

**Closed as completed by flrnd** 2020-09-22 09:31 UTC

**Comment by ghost** [comment] 2020-09-22 16:41
@flrnd Thank you. I am know some programming languages, but I am not familiar with vimscript. 
`CursorLine xxx ctermbg=234 guibg=#1c1c1c` 
Because in your code `let s:pale_black = s:colors.menublack` and ` "menublack": get(s:color_store, "menu_black", {'gui': '#1c1c1c', 'cterm256': '234'})`
So I believe is an issue in your code. Not a TERM issue.
this line should be `let s:pale_black = s:colors.black` instead of `let s:pale_black = s:colors.menublack`

**Comment by flrnd** [comment] 2020-09-22 20:47
Yes, you are right, it's not a Term issue. And I created more confusion because linked the wrong variable. Let me explain it better.

`CursorLine` highlights the current cursor line position, if you have either activated in your config or manually `:set cursorline`. 

>this line should be let s:pale_black = s:colors.black

Then there wouldn't be any hightlight at all because both backgrounds would be the same color. 

If you don't like the `cursorline` hightlight, then you have 2 options: Don't use it, or change the color. Choose your poison :)

Sorry for the confusion before.

**Comment by ghost** [comment] 2020-09-22 22:39
> Yes, you are right, it's not a Term issue. And I created more confusion because linked the wrong variable. Let me explain it better.
> 
> `CursorLine` highlights the current cursor line position, if you have either activated in your config or manually `:set cursorline`.
> 
> > this line should be let s:pale_black = s:colors.black
> 
> Then there wouldn't be any hightlight at all because both backgrounds would be the same color.
> 
> If you don't like the `cursorline` hightlight, then you have 2 options: Don't use it, or change the color. Choose your poison :)
> 
> Sorry for the confusion before.

Thank you for your explanation. I understand now. Yes, I will change the color to my liking. The reason I created an issue it was because the screenshot provided looked different than mine. Keep up the great work. Thank you again.
